django_webmaster_api/urls.py
from django.contrib import admin
from django.urls import path
from webmaster_api import urls as web_urls
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webmaster_api/', include(web_urls))

]

webmaster_api/urls.py
from django.contrib import admin
from django.urls import path
from webmaster_api.views import DataList, Operations, OperationDelete, OperationAdd
from django.views.generic import TemplateView, RedirectView

app_name="webmaster_api"

urlpatterns = [
    path('data/', DataList.as_view(), name="data"),
    path('operations/', Operations.as_view(), name="operations"),
    path('', TemplateView.as_view(template_name='base.html')),
    path('operations/delete/', OperationDelete.as_view(), name="delete_urls"),
    path('operations/add/', OperationAdd.as_view(), name="add_urls"),

]

webmaster_api/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Table(models.Model):

    domain = models.CharField(blank=True, max_length=100)
    fatal = models.IntegerField(null=True, default=0)
    critical = models.IntegerField(null=True, default=0)
    possible_problem = models.IntegerField(null=True, default=0)
    recommendation = models.IntegerField(null=True, default=0)
    sitemap_date = models.DateField(null=True, blank=True)
    sitemap_url_count = models.IntegerField(null=True, default=0)
    searchable_date = models.DateField(null=True, blank=True)
    searchable_count = models.IntegerField(null=True, default=0)

webmaster_api/views.py
from django.views.generic import ListView, View
from django.http import HttpResponse
from .models import Table
from .api import Data
from django.shortcuts import render, redirect

# Create your views here.


class DataList(ListView):
    queryset = Table.objects.all()
    context_object_name = 'data'
    template_name = 'data.html'

    def post(self, request):
        data = Data()
        work_time = data.get_data()
        return render(request, self.template_name, {'work_time': work_time, 'data': self.queryset})


class Operations(View):
    data = Data()
    user_ids = []
    for oauth_token in data.OAUTH_TOKENS:
        SESSION = data.auth(oauth_token)
        user_id = data.get_user_id(SESSION)
        user_ids.append(user_id)

    def get(self, request):

        return render(request, 'operations.html', {'user_ids': self.user_ids})

    def post(self, request):

        user_id = request.POST.get('user-id')
        SESSION = self.data.auth(self.data.OAUTH_TOKENS[self.data.user_ids.index(int(user_id))])
        # action_type = request.POST.get('user-id')
        urls = self.data.get_urls(user_id, SESSION)

        return render(request, 'operations.html', {'user_ids': self.user_ids, 'urls': urls})


class OperationDelete(Operations):

    def get(self, request):

        return redirect('/webmaster_api/operations/')

    def post(self, request):
        delete_urls = request.POST.get('delete-text')
        delete_urls = delete_urls.replace('.ru', '.ru/')
        delete_urls = delete_urls.split('\r\n')
        user_id = request.POST.get('user-id')
        SESSION = self.data.auth(self.data.OAUTH_TOKENS[self.data.user_ids.index(int(user_id))])

        r = SESSION.get(self.data.API_URL + '/user/' + str(user_id) + '/hosts/')
        c = r.json()
        hosts = c['hosts']
        host_ids = []
        for host in hosts:
            if host['ascii_host_url'] in delete_urls:
                host_ids.append(host['host_id'])

        for host_id in host_ids:
            path = '/user/' + str(user_id) + '/hosts/' + host_id
            # todo: убрать заглушку для удаления сайтов
            # response = SESSION.delete(self.data.API_URL + path)
        return render(request, 'delete.html', {'delete_urls': host_ids})


class OperationAdd(Operations):

    def get(self, request):

        return redirect('/webmaster_api/operations/')

    def post(self, request):
        add_urls = request.POST.get('add-text')
        add_urls = add_urls.replace('.ru', '.ru/')
        add_urls = add_urls.split('\r\n')
        user_id = request.POST.get('user-id')
        SESSION = self.data.auth(self.data.OAUTH_TOKENS[self.data.user_ids.index(int(user_id))])

        for url in add_urls:
            path = '/user/' + str(user_id) + '/hosts/'
            # todo: убрать заглушку для добавления сайтов
            # response = SESSION.post(self.data.API_URL + path, json={"host_url": url})

        return render(request, 'add.html', {'add_urls': add_urls})

templates/add.html
{% extends 'base.html' %}
{% block title %}
    Добавление сайтов
{% endblock %}
{% block content %}
    <div>
        <ul>Вы добавили следующие сайты:</ul>
{% for url in add_urls %}
            <li>{{ url }}</li>
{% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/data.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Анализ сайтов
        {% endblock %}
    </title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-info">Webmaster Dashboard</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/data/">Сводка</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/operations/">Операции над сайтами</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/data/">Подтверждение прав</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/data/">Оригинальные тексты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/data/">Операции над Sitemap</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/webmaster_api/data/">История сайта</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/data.html
{% extends 'base.html' %}
{% block title %}
    Сводка
{% endblock %}
{% block content %}

    <form class="add-token">{% csrf_token %}
      <div class="form-group">
        <label for="oauth-token">Ваш Access Token</label>
        <input type="text" class="form-control" id="oauth-token">
      </div>
      <button type="submit" class="btn btn-primary">Добавить</button>
    </form>

    <form action="{% url 'webmaster_api:data' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-primary">Обновить!</button>
    </form>

    {% if work_time is not None %}
    <p>{{ work_time }}</p>
    {% endif %}

    <table id="myTable" class="table table-striped table-bordered">
        <thead>
            <tr class="text-center">
                <th>Домен</th>
                <th>Фатальные ош</th>
                <th>Критические ош</th>
                <th>Возможные ош</th>
                <th>Рекомендации</th>
                <th>Проверка Sitemap</th>
                <th>Cсылок в Sitemap</th>
                <th>Проверка поисковых стр.</th>
                <th>Количество поисковых стр.</th>
            </tr>
        </thead>

            <tbody>
            {% for i in data %}
                <tr class="text-center">
                    <td class="text-left">{{ i.domain }}</td>
                    <td>{{ i.fatal }}</td>
                    <td>{{ i.critical }}</td>
                    <td>{{ i.possible_problem }}</td>
                    <td>{{ i.recommendation }}</td>
                    <td>{{ i.sitemap_date|date:"d F, Y" }}</td>
                    <td>{{ i.sitemap_url_count }}</td>
                    <td>{{ i.searchable_date|date:"d F, Y" }}</td>
                    <td>{{ i.searchable_count }}</td>
                </tr>
            {% endfor %}
            </tbody>

    </table>

    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block title %}
    Удаление сайтов
{% endblock %}
{% block content %}
    <div>
        <ul>Вы удалили следующие сайты:</ul>
{% for url in delete_urls %}
            <li>{{ url }}</li>
{% endfor %}
    </div>
{% endblock %}

templates/operations.html
{% extends 'base.html' %}
{% block title %}
    Операции над сайтами
{% endblock %}
{% block content %}

    <div class="center">
    {% if user_ids %}
        <form action="{% url 'webmaster_api:operations' %}" method="post" name="formUsers">{% csrf_token %}
            <div>Выберите один из user_id:</div>
            <select id="selectUserId" name="user-id">
            {% for user_id in user_ids %}
                <option value="{{ user_id }}">{{ user_id }}</option>
            {% endfor %}
            </select>
            <div>
                <button type="submit" class="btn btn-primary">Получить<br>список сайтов</button>
            </div>
        </form>
    {% else %}
        <div>Ваши user_id не обнаружены...</div>
    {% endif %}


    {% if urls %}
        <table id="urlTable" class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Ссылка</th>
                </tr>
            </thead>
                <tbody>
                {% for url in urls %}
                    <tr>
                        <td class="text-left">{{ url }}</td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
    {% endif %}
    </div>

    <div class="text-forms">
        <form action="{% url 'webmaster_api:delete_urls' %}" method="post" name="formDelete">{% csrf_token %}
            <input id="delUserId" name="user-id" type="text" hidden>
            <textarea id="delete-urls" name="delete-text" type="text" placeholder="Введите здесь список сайтов, которые необходимо удалить в формате https://(url).ru"></textarea>
            <div>
                <button type="submit" class="btn btn-primary">Удалить сайты</button>
            </div>
        </form>

        <form action="{% url 'webmaster_api:add_urls' %}" method="post" name="formDelete">{% csrf_token %}
            <input id="addUserId" name="user-id" type="text" hidden>
            <textarea id="add-urls" name="add-text" type="text" placeholder="Введите здесь список сайтов, которые необходимо добавить в формате https://(url).ru"></textarea>
            <div>
                <button type="submit" class="btn btn-primary">Добавить сайты</button>
            </div>
        </form>
    </div>

    <script>
    var e = document.getElementById("selectUserId");
    var strUser = e.options[e.selectedIndex].value;
    document.getElementById('delUserId').setAttribute('value', strUser);
    document.getElementById('addUserId').setAttribute('value', strUser);

    $(e).click( function () {
        strUser = e.options[e.selectedIndex].value;
        document.getElementById('delUserId').setAttribute('value', strUser);
        document.getElementById('addUserId').setAttribute('value', strUser);

    });
    $(document).ready( function () {
        $('#urlTable').DataTable({
            "scrollY": "500px",
            "scrollCollapse": true,
            "paging": false
        });
    });
    </script>
{% endblock %}